import type {
  Activity,
  AppNotification,
  Delivery,
  Issue,
  Merchant,
  Rider,
  TimelineEvent,
  Zone,
} from "./types";

export const zones: Zone[] = [
  {
    id: "z1",
    name: "Central",
    hubs: ["Hub Central · Kampala Rd", "Warehouse A · Industrial Area"],
    ridersOnline: 2,
    openOrders: 3,
    avgEtaMins: 16,
    coverage: "healthy",
    surge: 1.0,
  },
  {
    id: "z2",
    name: "East",
    hubs: ["Hub East · Bugolobi", "Cold Chain Hub · Luzira"],
    ridersOnline: 2,
    openOrders: 2,
    avgEtaMins: 22,
    coverage: "tight",
    surge: 1.15,
  },
  {
    id: "z3",
    name: "North",
    hubs: ["Pharmacy Depot · Ntinda", "Print Hub · Wandegeya"],
    ridersOnline: 1,
    openOrders: 1,
    avgEtaMins: 28,
    coverage: "healthy",
    surge: 1.0,
  },
  {
    id: "z4",
    name: "South",
    hubs: ["Warehouse B · Namanve"],
    ridersOnline: 0,
    openOrders: 1,
    avgEtaMins: 40,
    coverage: "critical",
    surge: 1.35,
  },
];

export const merchants: Merchant[] = [
  {
    id: "m1",
    name: "Cafe Javas",
    contact: "Diana A.",
    phone: "+256 772 100 200",
    address: "Nakasero Rd, Kampala",
    ordersToday: 14,
    openOrders: 2,
    avgPrepMins: 12,
    zone: "Central",
    settlement: "weekly",
  },
  {
    id: "m2",
    name: "Acacia Mall Store",
    contact: "James K.",
    phone: "+256 772 100 201",
    address: "Acacia Ave, Kololo",
    ordersToday: 9,
    openOrders: 1,
    avgPrepMins: 18,
    zone: "Central",
    settlement: "daily",
  },
  {
    id: "m3",
    name: "Ntinda Pharmacy Depot",
    contact: "Dr. Mutebi",
    phone: "+256 772 100 202",
    address: "Ntinda Shopping Centre",
    ordersToday: 6,
    openOrders: 1,
    avgPrepMins: 8,
    zone: "North",
    settlement: "weekly",
  },
  {
    id: "m4",
    name: "Tech Hub Co-working",
    contact: "Ops desk",
    phone: "+256 772 100 203",
    address: "Yusuf Lule Rd",
    ordersToday: 4,
    openOrders: 1,
    avgPrepMins: 5,
    zone: "Central",
    settlement: "weekly",
  },
  {
    id: "m5",
    name: "Village Market",
    contact: "Grace N.",
    phone: "+256 772 100 205",
    address: "Village Mall, Bugolobi",
    ordersToday: 11,
    openOrders: 0,
    avgPrepMins: 15,
    zone: "East",
    settlement: "daily",
  },
];

export const riders: Rider[] = [
  {
    id: "r1",
    name: "James Okello",
    phone: "+256 700 111 001",
    email: "james@haula.local",
    vehicle: "Motorcycle",
    plate: "UBE 421A",
    status: "on_delivery",
    rating: 4.9,
    deliveriesToday: 7,
    avgDeliveryMins: 28,
    onTimeRate: 96,
    avatarColor: "#f97316",
    lat: 0.3476,
    lng: 32.5825,
    zone: "Central",
    documentsOk: true,
    licenseExpiry: "2027-03-12",
    earningsWeek: 485000,
    activeJobs: 1,
    maxJobs: 3,
  },
  {
    id: "r2",
    name: "Sarah Namukasa",
    phone: "+256 700 111 002",
    email: "sarah@haula.local",
    vehicle: "Van",
    plate: "UAT 882B",
    status: "online",
    rating: 4.7,
    deliveriesToday: 4,
    avgDeliveryMins: 35,
    onTimeRate: 91,
    avatarColor: "#3b82f6",
    lat: 0.321,
    lng: 32.601,
    zone: "East",
    documentsOk: true,
    licenseExpiry: "2026-11-01",
    earningsWeek: 312000,
    activeJobs: 1,
    maxJobs: 3,
  },
  {
    id: "r3",
    name: "David Mugisha",
    phone: "+256 700 111 003",
    email: "david@haula.local",
    vehicle: "Motorcycle",
    plate: "UBF 119C",
    status: "on_delivery",
    rating: 4.8,
    deliveriesToday: 9,
    avgDeliveryMins: 24,
    onTimeRate: 98,
    avatarColor: "#22c55e",
    lat: 0.36,
    lng: 32.55,
    zone: "North",
    documentsOk: true,
    licenseExpiry: "2027-08-20",
    earningsWeek: 520000,
    activeJobs: 1,
    maxJobs: 3,
  },
  {
    id: "r4",
    name: "Amina Nakato",
    phone: "+256 700 111 004",
    email: "amina@haula.local",
    vehicle: "Motorcycle",
    plate: "UCD 330D",
    status: "break",
    rating: 4.6,
    deliveriesToday: 5,
    avgDeliveryMins: 31,
    onTimeRate: 88,
    avatarColor: "#a855f7",
    lat: 0.31,
    lng: 32.57,
    zone: "Central",
    documentsOk: true,
    licenseExpiry: "2026-09-15",
    earningsWeek: 290000,
    activeJobs: 0,
    maxJobs: 3,
  },
  {
    id: "r5",
    name: "Peter Ssenyonjo",
    phone: "+256 700 111 005",
    email: "peter@haula.local",
    vehicle: "Bike",
    plate: "UBE 905E",
    status: "offline",
    rating: 4.5,
    deliveriesToday: 0,
    avgDeliveryMins: 33,
    onTimeRate: 85,
    avatarColor: "#ef4444",
    lat: 0.34,
    lng: 32.61,
    zone: "South",
    documentsOk: false,
    licenseExpiry: "2025-12-01",
    earningsWeek: 0,
    activeJobs: 0,
    maxJobs: 2,
  },
  {
    id: "r6",
    name: "Grace Atim",
    phone: "+256 700 111 006",
    email: "grace@haula.local",
    vehicle: "Van",
    plate: "UAF 214F",
    status: "online",
    rating: 4.9,
    deliveriesToday: 3,
    avgDeliveryMins: 40,
    onTimeRate: 94,
    avatarColor: "#14b8a6",
    lat: 0.355,
    lng: 32.59,
    zone: "East",
    documentsOk: true,
    licenseExpiry: "2028-01-10",
    earningsWeek: 265000,
    activeJobs: 1,
    maxJobs: 3,
  },
];

export const deliveries: Delivery[] = [
  {
    id: "d1",
    trackingCode: "HAU-88421",
    merchantId: "m1",
    merchantName: "Cafe Javas",
    customer: "Diana Atim",
    customerPhone: "+256 772 100 200",
    pickup: "Warehouse A · Industrial Area",
    dropoff: "Nakasero Rd, Kampala",
    status: "in_transit",
    riderId: "r1",
    riderName: "James Okello",
    etaMins: 12,
    distanceKm: 4.2,
    fee: 15000,
    codAmount: 0,
    pickupLat: 0.313,
    pickupLng: 32.605,
    dropoffLat: 0.321,
    dropoffLng: 32.581,
    createdAt: "2026-07-23T07:42:00",
    assignedAt: "2026-07-23T07:50:00",
    pickedUpAt: "2026-07-23T08:05:00",
    deliveredAt: null,
    priority: "express",
    otp: "4821",
    podRequired: true,
    podVerified: false,
    podMethod: "otp_photo",
    trackToken: "trk_88421",
    zone: "Central",
    notes: "Leave with reception",
  },
  {
    id: "d2",
    trackingCode: "HAU-88422",
    merchantId: "m2",
    merchantName: "Acacia Mall Store",
    customer: "Acacia Mall Receiving",
    customerPhone: "+256 772 100 201",
    pickup: "Hub East · Bugolobi",
    dropoff: "Acacia Ave, Kololo",
    status: "picked_up",
    riderId: "r3",
    riderName: "David Mugisha",
    etaMins: 18,
    distanceKm: 6.1,
    fee: 22000,
    codAmount: 85000,
    pickupLat: 0.315,
    pickupLng: 32.62,
    dropoffLat: 0.335,
    dropoffLng: 32.59,
    createdAt: "2026-07-23T07:55:00",
    assignedAt: "2026-07-23T08:00:00",
    pickedUpAt: "2026-07-23T08:20:00",
    deliveredAt: null,
    priority: "same_day",
    otp: "9033",
    podRequired: true,
    podVerified: false,
    podMethod: "otp_photo",
    trackToken: "trk_88422",
    zone: "East",
  },
  {
    id: "d3",
    trackingCode: "HAU-88423",
    merchantId: "m3",
    merchantName: "Ntinda Pharmacy Depot",
    customer: "Dr. Mutebi Clinic",
    customerPhone: "+256 772 100 202",
    pickup: "Pharmacy Depot · Ntinda",
    dropoff: "Ntinda Shopping Centre",
    status: "assigned",
    riderId: "r2",
    riderName: "Sarah Namukasa",
    etaMins: 35,
    distanceKm: 8.4,
    fee: 28000,
    codAmount: 0,
    pickupLat: 0.36,
    pickupLng: 32.62,
    dropoffLat: 0.358,
    dropoffLng: 32.615,
    createdAt: "2026-07-23T08:10:00",
    assignedAt: "2026-07-23T08:12:00",
    pickedUpAt: null,
    deliveredAt: null,
    priority: "express",
    otp: "1150",
    podRequired: true,
    podVerified: false,
    podMethod: "otp_photo",
    trackToken: "trk_88423",
    zone: "North",
    notes: "Cold chain · keep upright",
  },
  {
    id: "d4",
    trackingCode: "HAU-88424",
    merchantId: "m4",
    merchantName: "Tech Hub Co-working",
    customer: "Tech Hub Front Desk",
    customerPhone: "+256 772 100 203",
    pickup: "Warehouse B · Namanve",
    dropoff: "Plot 4, Yusuf Lule Rd",
    status: "pending",
    riderId: null,
    riderName: null,
    etaMins: null,
    distanceKm: 14.2,
    fee: 45000,
    codAmount: 120000,
    pickupLat: 0.35,
    pickupLng: 32.68,
    dropoffLat: 0.325,
    dropoffLng: 32.585,
    createdAt: "2026-07-23T08:25:00",
    assignedAt: null,
    pickedUpAt: null,
    deliveredAt: null,
    priority: "standard",
    otp: "7742",
    podRequired: true,
    podVerified: false,
    podMethod: "otp_photo",
    trackToken: "trk_88424",
    zone: "South",
  },
  {
    id: "d5",
    trackingCode: "HAU-88418",
    merchantId: "m1",
    merchantName: "Cafe Javas",
    customer: "Garden City Food Court",
    customerPhone: "+256 772 100 204",
    pickup: "Hub Central · Kampala Rd",
    dropoff: "Garden City Mall",
    status: "delivered",
    riderId: "r3",
    riderName: "David Mugisha",
    etaMins: 0,
    distanceKm: 3.1,
    fee: 12000,
    codAmount: 0,
    pickupLat: 0.318,
    pickupLng: 32.582,
    dropoffLat: 0.33,
    dropoffLng: 32.585,
    createdAt: "2026-07-23T06:30:00",
    assignedAt: "2026-07-23T06:35:00",
    pickedUpAt: "2026-07-23T06:45:00",
    deliveredAt: "2026-07-23T07:08:00",
    priority: "express",
    otp: "2201",
    podRequired: true,
    podVerified: true,
    podMethod: "otp_photo",
    trackToken: "trk_88418",
    zone: "Central",
  },
  {
    id: "d6",
    trackingCode: "HAU-88419",
    merchantId: "m5",
    merchantName: "Village Market",
    customer: "Village Market Receiving",
    customerPhone: "+256 772 100 205",
    pickup: "Cold Chain Hub · Luzira",
    dropoff: "Village Mall, Bugolobi",
    status: "delivered",
    riderId: "r1",
    riderName: "James Okello",
    etaMins: 0,
    distanceKm: 5.5,
    fee: 18000,
    codAmount: 45000,
    pickupLat: 0.3,
    pickupLng: 32.655,
    dropoffLat: 0.312,
    dropoffLng: 32.625,
    createdAt: "2026-07-23T06:15:00",
    assignedAt: "2026-07-23T06:20:00",
    pickedUpAt: "2026-07-23T06:40:00",
    deliveredAt: "2026-07-23T07:15:00",
    priority: "same_day",
    otp: "6618",
    podRequired: true,
    podVerified: true,
    podMethod: "otp_photo",
    trackToken: "trk_88419",
    zone: "East",
  },
  {
    id: "d7",
    trackingCode: "HAU-88425",
    merchantId: "m4",
    merchantName: "Tech Hub Co-working",
    customer: "Makerere Bookshop",
    customerPhone: "+256 772 100 206",
    pickup: "Print Hub · Wandegeya",
    dropoff: "Makerere University Main Gate",
    status: "in_transit",
    riderId: "r6",
    riderName: "Grace Atim",
    etaMins: 8,
    distanceKm: 2.4,
    fee: 10000,
    codAmount: 0,
    pickupLat: 0.335,
    pickupLng: 32.57,
    dropoffLat: 0.333,
    dropoffLng: 32.568,
    createdAt: "2026-07-23T08:30:00",
    assignedAt: "2026-07-23T08:35:00",
    pickedUpAt: "2026-07-23T08:48:00",
    deliveredAt: null,
    priority: "standard",
    otp: "3390",
    podRequired: false,
    podVerified: false,
    podMethod: null,
    trackToken: "trk_88425",
    zone: "North",
  },
  {
    id: "d8",
    trackingCode: "HAU-88420",
    merchantId: "m2",
    merchantName: "Acacia Mall Store",
    customer: "Kisementi Bistro",
    customerPhone: "+256 772 100 207",
    pickup: "Warehouse A · Industrial Area",
    dropoff: "Kisementi, Kamwokya",
    status: "failed",
    riderId: "r4",
    riderName: "Amina Nakato",
    etaMins: null,
    distanceKm: 7.0,
    fee: 20000,
    codAmount: 0,
    pickupLat: 0.313,
    pickupLng: 32.605,
    dropoffLat: 0.34,
    dropoffLng: 32.585,
    createdAt: "2026-07-23T07:00:00",
    assignedAt: "2026-07-23T07:05:00",
    pickedUpAt: "2026-07-23T07:20:00",
    deliveredAt: null,
    priority: "standard",
    otp: "5500",
    podRequired: true,
    podVerified: false,
    podMethod: "otp_photo",
    failReason: "customer_unavailable",
    trackToken: "trk_88420",
    zone: "Central",
  },
  {
    id: "d9",
    trackingCode: "HAU-88426",
    merchantId: "m1",
    merchantName: "Cafe Javas",
    customer: "Kololo Heights Apt 4B",
    customerPhone: "+256 772 100 208",
    pickup: "Cafe Javas · Garden City",
    dropoff: "Kololo Hill Drive",
    status: "pending",
    riderId: null,
    riderName: null,
    etaMins: null,
    distanceKm: 3.8,
    fee: 14000,
    codAmount: 32000,
    pickupLat: 0.33,
    pickupLng: 32.585,
    dropoffLat: 0.338,
    dropoffLng: 32.592,
    createdAt: "2026-07-23T08:40:00",
    assignedAt: null,
    pickedUpAt: null,
    deliveredAt: null,
    priority: "express",
    otp: "8812",
    podRequired: true,
    podVerified: false,
    podMethod: "otp_photo",
    trackToken: "trk_88426",
    zone: "Central",
  },
];

export const issues: Issue[] = [
  {
    id: "i1",
    type: "failed_delivery",
    status: "open",
    title: "Customer unavailable — needs reattempt",
    detail: "HAU-88420 failed at Kisementi. Customer asked for 2–4 PM window.",
    deliveryId: "d8",
    trackingCode: "HAU-88420",
    riderName: "Amina Nakato",
    createdAt: "2026-07-23T07:45:00",
    priority: "high",
  },
  {
    id: "i2",
    type: "payment",
    status: "in_progress",
    title: "COD mismatch on HAU-88419",
    detail: "Rider collected UGX 40,000 · invoice expected UGX 45,000.",
    deliveryId: "d6",
    trackingCode: "HAU-88419",
    riderName: "James Okello",
    createdAt: "2026-07-23T07:30:00",
    priority: "medium",
  },
  {
    id: "i3",
    type: "wrong_address",
    status: "open",
    title: "Dropoff pin unclear · South zone",
    detail: "Merchant provided Plot 4 but gate code missing for HAU-88424.",
    deliveryId: "d4",
    trackingCode: "HAU-88424",
    createdAt: "2026-07-23T08:28:00",
    priority: "medium",
  },
  {
    id: "i4",
    type: "rider_conduct",
    status: "resolved",
    title: "Late pickup complaint",
    detail: "Merchant flagged 18 min wait. Resolved with credit.",
    trackingCode: "HAU-88415",
    riderName: "Peter Ssenyonjo",
    createdAt: "2026-07-22T16:10:00",
    priority: "low",
  },
  {
    id: "i5",
    type: "damage",
    status: "open",
    title: "Package seal broken on arrival",
    detail: "Customer photo attached. Awaiting merchant decision.",
    trackingCode: "HAU-88410",
    riderName: "Grace Atim",
    createdAt: "2026-07-22T19:40:00",
    priority: "high",
  },
];

export const notifications: AppNotification[] = [
  {
    id: "n1",
    title: "2 orders unassigned > 10 min",
    body: "HAU-88424 and HAU-88426 still waiting in dispatch.",
    time: "2 min ago",
    read: false,
    href: "/dispatch",
    level: "critical",
  },
  {
    id: "n2",
    title: "South zone coverage critical",
    body: "0 riders online · surge 1.35× suggested.",
    time: "8 min ago",
    read: false,
    href: "/zones",
    level: "warn",
  },
  {
    id: "n3",
    title: "Failed delivery needs reattempt",
    body: "HAU-88420 · customer unavailable.",
    time: "1 hr ago",
    read: false,
    href: "/issues",
    level: "warn",
  },
  {
    id: "n4",
    title: "POD verified",
    body: "HAU-88418 delivered by David Mugisha.",
    time: "2 hr ago",
    read: true,
    href: "/deliveries/d5",
    level: "info",
  },
  {
    id: "n5",
    title: "Rider docs expired",
    body: "Peter Ssenyonjo license expired — cannot go online.",
    time: "Yesterday",
    read: true,
    href: "/riders/r5",
    level: "warn",
  },
];

export const activities: Activity[] = [
  {
    id: "a1",
    type: "delivery",
    message: "James Okello picked up HAU-88421",
    time: "8:05 AM",
    meta: "ETA 12 min",
  },
  {
    id: "a2",
    type: "rider",
    message: "Sarah Namukasa went online",
    time: "8:02 AM",
  },
  {
    id: "a3",
    type: "delivery",
    message: "HAU-88418 delivered · POD + OTP verified",
    time: "7:08 AM",
    meta: "23 min · on time",
  },
  {
    id: "a4",
    type: "alert",
    message: "HAU-88424 waiting in dispatch queue",
    time: "8:25 AM",
    meta: "14.2 km · standard",
  },
  {
    id: "a5",
    type: "delivery",
    message: "David Mugisha en route · HAU-88422",
    time: "8:20 AM",
    meta: "ETA 18 min · COD 85K",
  },
  {
    id: "a6",
    type: "alert",
    message: "HAU-88420 failed · customer unavailable",
    time: "7:45 AM",
    meta: "Issue opened",
  },
];

export const hourlyOrders = [
  { hour: "6a", orders: 2, onTime: 2 },
  { hour: "7a", orders: 6, onTime: 5 },
  { hour: "8a", orders: 9, onTime: 8 },
  { hour: "9a", orders: 7, onTime: 6 },
  { hour: "10a", orders: 5, onTime: 5 },
  { hour: "11a", orders: 4, onTime: 4 },
  { hour: "12p", orders: 8, onTime: 7 },
  { hour: "1p", orders: 6, onTime: 5 },
];

export const dashboardStats = {
  activeRiders: 4,
  liveDeliveries: 5,
  unassigned: 2,
  avgEtaMins: 18,
  onTimeRate: 92,
  onTimeDelta: 1.8,
  deliveredToday: 2,
  failedToday: 1,
  gmvToday: 184000,
  codOutstanding: 237000,
  openIssues: 4,
};

export function formatUgx(amount: number) {
  return new Intl.NumberFormat("en-UG", {
    style: "currency",
    currency: "UGX",
    maximumFractionDigits: 0,
  }).format(amount);
}

export function statusLabel(status: Delivery["status"]) {
  const map: Record<Delivery["status"], string> = {
    pending: "Pending",
    assigned: "Assigned",
    picked_up: "Picked up",
    in_transit: "In transit",
    delivered: "Delivered",
    failed: "Failed",
    cancelled: "Cancelled",
  };
  return map[status];
}

export function riderStatusLabel(status: Rider["status"]) {
  const map: Record<Rider["status"], string> = {
    online: "Online",
    on_delivery: "On delivery",
    offline: "Offline",
    break: "On break",
  };
  return map[status];
}

export function getDeliveryByTrack(codeOrToken: string) {
  const key = codeOrToken.toLowerCase();
  return deliveries.find(
    (d) =>
      d.trackingCode.toLowerCase() === key ||
      d.trackToken.toLowerCase() === key ||
      d.trackingCode.toLowerCase().replace("hau-", "") ===
        key.replace("hau-", ""),
  );
}

export function getDelivery(id: string) {
  return deliveries.find((d) => d.id === id);
}

export function getRider(id: string) {
  return riders.find((r) => r.id === id);
}

export function failReasonLabel(reason?: Delivery["failReason"]) {
  if (!reason) return "—";
  const map = {
    customer_unavailable: "Customer unavailable",
    wrong_address: "Wrong address",
    refused: "Refused package",
    damaged: "Damaged in transit",
    other: "Other",
  };
  return map[reason];
}

export function buildTimeline(d: Delivery): TimelineEvent[] {
  const order = [
    "pending",
    "assigned",
    "picked_up",
    "in_transit",
    "delivered",
  ] as const;
  const idx = order.indexOf(d.status as (typeof order)[number]);

  if (d.status === "failed") {
    return [
      { label: "Created", at: d.createdAt, done: true },
      { label: "Assigned", at: d.assignedAt, done: !!d.assignedAt },
      { label: "Picked up", at: d.pickedUpAt, done: !!d.pickedUpAt },
      {
        label: `Failed · ${failReasonLabel(d.failReason)}`,
        at: d.pickedUpAt,
        done: true,
        current: true,
      },
    ];
  }

  return [
    {
      label: "Created",
      at: d.createdAt,
      done: true,
      current: d.status === "pending",
    },
    {
      label: "Assigned",
      at: d.assignedAt,
      done: idx >= 1,
      current: d.status === "assigned",
    },
    {
      label: "Picked up",
      at: d.pickedUpAt,
      done: idx >= 2,
      current: d.status === "picked_up",
    },
    {
      label: "In transit",
      at: d.pickedUpAt && idx >= 3 ? d.pickedUpAt : null,
      done: idx >= 3,
      current: d.status === "in_transit",
    },
    {
      label: "Delivered",
      at: d.deliveredAt,
      done: d.status === "delivered",
      current: d.status === "delivered",
    },
  ];
}

export function formatTime(iso: string | null) {
  if (!iso) return "—";
  return new Date(iso).toLocaleTimeString([], {
    hour: "2-digit",
    minute: "2-digit",
  });
}
